version: "3.8"
services:
    postgres:
        image: "postgres:12"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=reseller_cashback
        ports:
            - 5432:5432
        volumes:
            - .reseller-cashback-pgdata:/var/lib/postgresql/data
