version: "3.8"
services:
    postgres:
        image: "postgres:12"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=reseller_cashback
        ports:
            - 5432:5432
        volumes:
            - ../.reseller-cashback-pgdata:/var/lib/postgresql/data

    migrations:
        build:
          context: .
          dockerfile: Dockerfile
        image: reseller-cashback:latest
        entrypoint: poetry run python reseller_cashback_api/manage.py migrate
        depends_on:
          - postgres
        environment:
          - SECRET_KEY=${SECRET_KEY}
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
          - EXTERNAL_API_BASE_URL=${EXTERNAL_API_BASE_URL}
          - EXTERNAL_API_TOKEN=${EXTERNAL_API_TOKEN}

    web:
        build:
          context: .
          dockerfile: Dockerfile
        image: reseller-cashback:latest
        depends_on:
          - migrations
        ports:
          - 127.0.0.1:8000:8000
        environment:
          - SECRET_KEY=${SECRET_KEY}
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
          - EXTERNAL_API_BASE_URL=${EXTERNAL_API_BASE_URL}
          - EXTERNAL_API_TOKEN=${EXTERNAL_API_TOKEN}
